create table TB_PRODUTO(
    COD_PRODUTO INTEGER not null ,
    DESC_PRODUTO VARCHAR(100) not null ,
    STA_STATUS VARCHAR(100) not null,
    primary key (COD_PRODUTO)
);

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESC_PRODUTO, STA_STATUS)  VALUES (0001, 'TESTE', 'TESTE')

